POST  http://127.0.0.1/product/create
Content-Type: application/json

{
    "title": "Sản phẩm mới 19",
    "slug": "san-pham-moi-19",
    "summary": "",
    "discount": 1,
    "quantity": 0
}

###
PATCH http://127.0.0.1/product/update/624a282c3c727249565e19ad
Content-Type: application/json

{
    "title": "Sản phẩm mới 18",
    "slug": "san-pham-moi-19",
    "summary": "",
    "discount": "1.5",
    "quantity": 0,
    "images": ["img1", "img2"]
}

###
DELETE  http://127.0.0.1/product/remove/6249fbce859fb3e07e0d14f1